plugins {
    id 'com.android.library'
}

android {
    namespace 'com.google.android.chimeraresources'
    compileSdkVersion androidCompileSdk

    defaultConfig {
        versionName version
        minSdkVersion androidMinSdk
        targetSdkVersion androidTargetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
