// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/mcs.proto
package org.microg.gms.gcm.mcs;

import com.squareup.wire.Message;

/**
 * TAG: 4
 */
public final class Close extends Message {

  public Close() {
  }

  private Close(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Close;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Close> {

    public Builder() {
    }

    public Builder(Close message) {
      super(message);
    }

    @Override
    public Close build() {
      return new Close(this);
    }
  }
}
