android.useAndroidX=true
android.builder.sdkDownload=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx6144m -XX:+UseParallelGC --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED -Djavax.net.ssl.trustStoreType=Windows-ROOT
kotlin.daemon.jvmargs=-Xmx3072m
