// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class AckAsset extends Message {

  public static final String DEFAULT_DIGEST = "";

  @ProtoField(tag = 1, type = STRING)
  public final String digest;

  public AckAsset(String digest) {
    this.digest = digest;
  }

  private AckAsset(Builder builder) {
    this(builder.digest);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AckAsset)) return false;
    return equals(digest, ((AckAsset) other).digest);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = digest != null ? digest.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<AckAsset> {

    public String digest;

    public Builder() {
    }

    public Builder(AckAsset message) {
      super(message);
      if (message == null) return;
      this.digest = message.digest;
    }

    public Builder digest(String digest) {
      this.digest = digest;
      return this;
    }

    @Override
    public AckAsset build() {
      return new AckAsset(this);
    }
  }
}
