// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;

public final class Asset extends Message {

  public Asset() {
  }

  private Asset(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Asset;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Asset> {

    public Builder() {
    }

    public Builder(Asset message) {
      super(message);
    }

    @Override
    public Asset build() {
      return new Asset(this);
    }
  }
}
