// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class ChannelDataAckRequest extends Message {

  public static final Boolean DEFAULT_FINALMESSAGE = false;

  @ProtoField(tag = 1)
  public final ChannelDataHeader header;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean finalMessage;

  public ChannelDataAckRequest(ChannelDataHeader header, Boolean finalMessage) {
    this.header = header;
    this.finalMessage = finalMessage;
  }

  private ChannelDataAckRequest(Builder builder) {
    this(builder.header, builder.finalMessage);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ChannelDataAckRequest)) return false;
    ChannelDataAckRequest o = (ChannelDataAckRequest) other;
    return equals(header, o.header)
        && equals(finalMessage, o.finalMessage);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = header != null ? header.hashCode() : 0;
      result = result * 37 + (finalMessage != null ? finalMessage.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ChannelDataAckRequest> {

    public ChannelDataHeader header;
    public Boolean finalMessage;

    public Builder() {
    }

    public Builder(ChannelDataAckRequest message) {
      super(message);
      if (message == null) return;
      this.header = message.header;
      this.finalMessage = message.finalMessage;
    }

    public Builder header(ChannelDataHeader header) {
      this.header = header;
      return this;
    }

    public Builder finalMessage(Boolean finalMessage) {
      this.finalMessage = finalMessage;
      return this;
    }

    @Override
    public ChannelDataAckRequest build() {
      return new ChannelDataAckRequest(this);
    }
  }
}
