// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;

public final class Connect extends Message {

  public static final Integer DEFAULT_ID = 0;
  public static final String DEFAULT_NAME = "";
  public static final Long DEFAULT_PEERANDROIDID = 0L;
  public static final Integer DEFAULT_UNKNOWN4 = 0;
  public static final Integer DEFAULT_UNKNOWN5 = 0;
  public static final Integer DEFAULT_UNKNOWN6 = 0;
  public static final String DEFAULT_NETWORKID = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer id;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  @ProtoField(tag = 3, type = INT64)
  public final Long peerAndroidId;

  @ProtoField(tag = 4, type = INT32)
  public final Integer unknown4;

  @ProtoField(tag = 5, type = INT32)
  public final Integer unknown5;

  @ProtoField(tag = 6, type = INT32)
  public final Integer unknown6;

  @ProtoField(tag = 7, type = STRING)
  public final String networkId;

  public Connect(Integer id, String name, Long peerAndroidId, Integer unknown4, Integer unknown5, Integer unknown6, String networkId) {
    this.id = id;
    this.name = name;
    this.peerAndroidId = peerAndroidId;
    this.unknown4 = unknown4;
    this.unknown5 = unknown5;
    this.unknown6 = unknown6;
    this.networkId = networkId;
  }

  private Connect(Builder builder) {
    this(builder.id, builder.name, builder.peerAndroidId, builder.unknown4, builder.unknown5, builder.unknown6, builder.networkId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Connect)) return false;
    Connect o = (Connect) other;
    return equals(id, o.id)
        && equals(name, o.name)
        && equals(peerAndroidId, o.peerAndroidId)
        && equals(unknown4, o.unknown4)
        && equals(unknown5, o.unknown5)
        && equals(unknown6, o.unknown6)
        && equals(networkId, o.networkId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = id != null ? id.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (peerAndroidId != null ? peerAndroidId.hashCode() : 0);
      result = result * 37 + (unknown4 != null ? unknown4.hashCode() : 0);
      result = result * 37 + (unknown5 != null ? unknown5.hashCode() : 0);
      result = result * 37 + (unknown6 != null ? unknown6.hashCode() : 0);
      result = result * 37 + (networkId != null ? networkId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Connect> {

    public Integer id;
    public String name;
    public Long peerAndroidId;
    public Integer unknown4;
    public Integer unknown5;
    public Integer unknown6;
    public String networkId;

    public Builder() {
    }

    public Builder(Connect message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
      this.name = message.name;
      this.peerAndroidId = message.peerAndroidId;
      this.unknown4 = message.unknown4;
      this.unknown5 = message.unknown5;
      this.unknown6 = message.unknown6;
      this.networkId = message.networkId;
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder peerAndroidId(Long peerAndroidId) {
      this.peerAndroidId = peerAndroidId;
      return this;
    }

    public Builder unknown4(Integer unknown4) {
      this.unknown4 = unknown4;
      return this;
    }

    public Builder unknown5(Integer unknown5) {
      this.unknown5 = unknown5;
      return this;
    }

    public Builder unknown6(Integer unknown6) {
      this.unknown6 = unknown6;
      return this;
    }

    public Builder networkId(String networkId) {
      this.networkId = networkId;
      return this;
    }

    @Override
    public Connect build() {
      return new Connect(this);
    }
  }
}
