// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;

public final class Heartbeat extends Message {

  public Heartbeat() {
  }

  private Heartbeat(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Heartbeat;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Heartbeat> {

    public Builder() {
    }

    public Builder(Heartbeat message) {
      super(message);
    }

    @Override
    public Heartbeat build() {
      return new Heartbeat(this);
    }
  }
}
