// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class SetDataItem extends Message {

  public static final String DEFAULT_PACKAGENAME = "";
  public static final String DEFAULT_URI = "";
  public static final List<String> DEFAULT_UNKNOWN3 = Collections.emptyList();
  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;
  public static final Long DEFAULT_SEQID = 0L;
  public static final Boolean DEFAULT_DELETED = false;
  public static final String DEFAULT_SOURCE = "";
  public static final List<AssetEntry> DEFAULT_ASSETS = Collections.emptyList();
  public static final String DEFAULT_SIGNATUREDIGEST = "";
  public static final Long DEFAULT_LASTMODIFIED = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String packageName;

  @ProtoField(tag = 2, type = STRING)
  public final String uri;

  @ProtoField(tag = 3, type = STRING, label = REPEATED)
  public final List<String> unknown3;

  @ProtoField(tag = 4, type = BYTES)
  public final ByteString data;

  @ProtoField(tag = 5, type = INT64)
  public final Long seqId;

  @ProtoField(tag = 6, type = BOOL)
  public final Boolean deleted;

  @ProtoField(tag = 7, type = STRING)
  public final String source;

  @ProtoField(tag = 8, label = REPEATED, messageType = AssetEntry.class)
  public final List<AssetEntry> assets;

  @ProtoField(tag = 9, type = STRING)
  public final String signatureDigest;

  @ProtoField(tag = 10, type = INT64)
  public final Long lastModified;

  public SetDataItem(String packageName, String uri, List<String> unknown3, ByteString data, Long seqId, Boolean deleted, String source, List<AssetEntry> assets, String signatureDigest, Long lastModified) {
    this.packageName = packageName;
    this.uri = uri;
    this.unknown3 = immutableCopyOf(unknown3);
    this.data = data;
    this.seqId = seqId;
    this.deleted = deleted;
    this.source = source;
    this.assets = immutableCopyOf(assets);
    this.signatureDigest = signatureDigest;
    this.lastModified = lastModified;
  }

  private SetDataItem(Builder builder) {
    this(builder.packageName, builder.uri, builder.unknown3, builder.data, builder.seqId, builder.deleted, builder.source, builder.assets, builder.signatureDigest, builder.lastModified);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SetDataItem)) return false;
    SetDataItem o = (SetDataItem) other;
    return equals(packageName, o.packageName)
        && equals(uri, o.uri)
        && equals(unknown3, o.unknown3)
        && equals(data, o.data)
        && equals(seqId, o.seqId)
        && equals(deleted, o.deleted)
        && equals(source, o.source)
        && equals(assets, o.assets)
        && equals(signatureDigest, o.signatureDigest)
        && equals(lastModified, o.lastModified);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = packageName != null ? packageName.hashCode() : 0;
      result = result * 37 + (uri != null ? uri.hashCode() : 0);
      result = result * 37 + (unknown3 != null ? unknown3.hashCode() : 1);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      result = result * 37 + (seqId != null ? seqId.hashCode() : 0);
      result = result * 37 + (deleted != null ? deleted.hashCode() : 0);
      result = result * 37 + (source != null ? source.hashCode() : 0);
      result = result * 37 + (assets != null ? assets.hashCode() : 1);
      result = result * 37 + (signatureDigest != null ? signatureDigest.hashCode() : 0);
      result = result * 37 + (lastModified != null ? lastModified.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SetDataItem> {

    public String packageName;
    public String uri;
    public List<String> unknown3;
    public ByteString data;
    public Long seqId;
    public Boolean deleted;
    public String source;
    public List<AssetEntry> assets;
    public String signatureDigest;
    public Long lastModified;

    public Builder() {
    }

    public Builder(SetDataItem message) {
      super(message);
      if (message == null) return;
      this.packageName = message.packageName;
      this.uri = message.uri;
      this.unknown3 = copyOf(message.unknown3);
      this.data = message.data;
      this.seqId = message.seqId;
      this.deleted = message.deleted;
      this.source = message.source;
      this.assets = copyOf(message.assets);
      this.signatureDigest = message.signatureDigest;
      this.lastModified = message.lastModified;
    }

    public Builder packageName(String packageName) {
      this.packageName = packageName;
      return this;
    }

    public Builder uri(String uri) {
      this.uri = uri;
      return this;
    }

    public Builder unknown3(List<String> unknown3) {
      this.unknown3 = checkForNulls(unknown3);
      return this;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    public Builder seqId(Long seqId) {
      this.seqId = seqId;
      return this;
    }

    public Builder deleted(Boolean deleted) {
      this.deleted = deleted;
      return this;
    }

    public Builder source(String source) {
      this.source = source;
      return this;
    }

    public Builder assets(List<AssetEntry> assets) {
      this.assets = checkForNulls(assets);
      return this;
    }

    public Builder signatureDigest(String signatureDigest) {
      this.signatureDigest = signatureDigest;
      return this;
    }

    public Builder lastModified(Long lastModified) {
      this.lastModified = lastModified;
      return this;
    }

    @Override
    public SetDataItem build() {
      return new SetDataItem(this);
    }
  }
}
