// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/wearable.proto
package org.microg.gms.wearable;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;

public final class SyncTableEntry extends Message {

  public static final String DEFAULT_KEY = "";
  public static final Long DEFAULT_VALUE = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String key;

  @ProtoField(tag = 2, type = INT64)
  public final Long value;

  public SyncTableEntry(String key, Long value) {
    this.key = key;
    this.value = value;
  }

  private SyncTableEntry(Builder builder) {
    this(builder.key, builder.value);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SyncTableEntry)) return false;
    SyncTableEntry o = (SyncTableEntry) other;
    return equals(key, o.key)
        && equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = key != null ? key.hashCode() : 0;
      result = result * 37 + (value != null ? value.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SyncTableEntry> {

    public String key;
    public Long value;

    public Builder() {
    }

    public Builder(SyncTableEntry message) {
      super(message);
      if (message == null) return;
      this.key = message.key;
      this.value = message.value;
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder value(Long value) {
      this.value = value;
      return this;
    }

    @Override
    public SyncTableEntry build() {
      return new SyncTableEntry(this);
    }
  }
}
