/* SPDX-License-Identifier: Apache-2.0 */
package org.microg.gms.smartdevice.directtransfer

internal enum class SourceTransferDiagnosticPhase {
    START, HANDSHAKE, OPTIONS, CONSENT, ENROLLMENT, CHALLENGE, ASSERTION, VERIFICATION, WRITE, RESULTS, FINAL_ACK, COMPLETION
}

/** Fixed checkpoints only. Never derive these codes from a request, account or exception text. */
internal enum class SourceTransferDiagnosticReason {
    SESSION_NOT_CURRENT, CALLER_CHANGED, TRANSPORT_CLOSED, CALLER_DISCONNECTED,
    CONSENT_OPTIONS, CONSENT_PEER, CONSENT_CREDENTIAL, CONSENT_PROFILE,
    CONSENT_ACCOUNT_QUERY, CONSENT_NO_LOCAL_ACCOUNT, CONSENT_NO_ELIGIBLE_ACCOUNT,
    CONSENT_REGISTRATION, CONSENT_INTENT, CONSENT_CALLBACK, CONSENT_RESULT,
    CONSENT_SELECTION, CONSENT_ALREADY_AUTHORIZED,
    // Protocol guards use only fixed locations, never field names or values received on the wire.
    PROTOCOL_COMPLETE,
    PROTOCOL_MESSAGE_LIMIT,
    PROTOCOL_VERSION,
    PROTOCOL_REMOTE_CANCEL,
    PROTOCOL_REMOTE_ERROR,
    PROTOCOL_REMOTE_STATE,
    PROTOCOL_DEVICE_STATUS,
    PROTOCOL_MESSAGE_CONTENT,
    PROTOCOL_MESSAGE_STATE,
    PROTOCOL_MESSAGE_EMPTY,
    PROTOCOL_FINAL_STATE,
    PROTOCOL_OPTIONS_ORDER,
    PROTOCOL_OPTIONS_DEVICE,
    PROTOCOL_OPTIONS_SESSION,
    PROTOCOL_OPTIONS_VERIFICATION,
    PROTOCOL_CREDENTIAL_ORDER,
    PROTOCOL_CREDENTIAL_FIELDS,
    PROTOCOL_CREDENTIAL_UNEXPECTED,
    PROTOCOL_CREDENTIAL_FORMAT,
    PROTOCOL_CREDENTIAL_COUNT,
    PROTOCOL_CREDENTIAL_ACCOUNT,
    PROTOCOL_CREDENTIAL_STATUS,
    PROTOCOL_VERIFICATION_URL,
    PROTOCOL_CHECKPOINT_VALUE,
    WEB_ISOLATION_UNAVAILABLE,
    WEB_AUTHENTICATION,
    WEB_AUTH_URL,
    WEB_NAVIGATION,
    WEB_TLS,
    WEB_LOAD,
    PROTOCOL_CONSENT_COUNT,
    PROTOCOL_CONSENT_ACCOUNT,
    PROTOCOL_BOOTSTRAP_IDENTITY,
    PROTOCOL_CHALLENGE_ORDER,
    PROTOCOL_CHALLENGE_FIELDS,
    PROTOCOL_CHALLENGE_PAYLOAD,
    PROTOCOL_CHALLENGE_COUNT,
    PROTOCOL_CHALLENGE_ENTRY,
    PROTOCOL_CHALLENGE_STATUS,
    PROTOCOL_CHALLENGE_ACCOUNT,
    PROTOCOL_CHECKIN_MISSING,
    PROTOCOL_CHECKIN_CHANGED,
    PROTOCOL_ASSERTION_SIZE,
    PROTOCOL_RESULT_ORDER,
    PROTOCOL_RESULT_COUNT,
    PROTOCOL_RESULT_ENTRY,
    PROTOCOL_RESULT_FIELDS,
    PROTOCOL_RESULT_ACCOUNT_FORMAT,
    PROTOCOL_RESULT_ACCOUNT,
    PROTOCOL_RESULT_STATUS_FORMAT,
    PROTOCOL_RESULT_STATUS,
    PROTOCOL_OUTGOING_SIZE,
    PROTOCOL_CLOSED,
    PROTOCOL_AUTH_ACCOUNT_CHANGED,
    PROTOCOL_INCOMING_SIZE,
    PROTOCOL_JSON_SYNTAX,
    PROTOCOL_JSON_DEPTH,
    PROTOCOL_JSON_ROOT,
    PROTOCOL_JSON_TRAILING,
    PROTOCOL_FIELD_UNKNOWN,
    PROTOCOL_FIELD_OBJECT,
    PROTOCOL_FIELD_ARRAY,
    PROTOCOL_FIELD_INTEGER,
    PROTOCOL_FIELD_STRING,
    PROTOCOL_FIELD_BINARY_TYPE,
    PROTOCOL_FIELD_BINARY_SIZE,
    PROTOCOL_FIELD_BINARY_ALPHABET,
    PROTOCOL_FIELD_BINARY_DECODE,
    PROTOCOL_FIELD_BINARY_VALUE
}

/** Receives the exception's class only; the message and cause cannot enter this diagnostic. */
internal fun sourceTransferFailureSummary(
    phase: SourceTransferDiagnosticPhase,
    kind: Class<out Throwable>,
    reason: SourceTransferDiagnosticReason? = null
): String = "${phase.name} failed (${kind.simpleName.ifEmpty { "Exception" }})" +
    (reason?.let { " reason=${it.name}" } ?: "")
