/*
 * SPDX-FileCopyrightText: 2020, microG Project Team
 * SPDX-License-Identifier: Apache-2.0
 */

apply plugin: 'com.squareup.wire'
apply plugin: 'kotlin'

dependencies {
    implementation "com.squareup.wire:wire-runtime:$wireVersion"
    api "com.squareup.wire:wire-grpc-client:$wireVersion"
}

wire {
    kotlin {
        javaInterop = true
    }
}

sourceSets {
    main.java.srcDirs += "$buildDir/generated/source/wire"
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_18
    targetCompatibility = JavaVersion.VERSION_18
}

compileKotlin {
    kotlinOptions.jvmTarget = "18"
}

compileTestKotlin {
    kotlinOptions.jvmTarget = "18"
}
