/* SPDX-License-Identifier: Apache-2.0 */
package org.microg.gms.smartdevice.directtransfer

import org.microg.gms.smartdevice.proto.Ukey2ClientInit
import org.microg.gms.smartdevice.proto.Ukey2Message
import org.microg.gms.smartdevice.proto.Ukey2MessageType
import java.security.KeyFactory
import java.security.KeyPair
import java.security.SecureRandom
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec
import java.util.Base64
import java.util.Properties

internal object DirectTransferTestFixture {
    // Generated by the unmodified google/ukey2 Java reference at
    // 10fc737aa901e873a3367e7e26b88eb01cd55d69. All keys are synthetic test keys.
    private val data = Properties().apply {
        requireNotNull(DirectTransferTestFixture::class.java.getResourceAsStream("/smartdevice/ukey2-google-v1.properties")).use(::load)
    }

    fun bytes(name: String): ByteArray = Base64.getDecoder().decode(requireNotNull(data.getProperty(name)))

    fun serverPair(): KeyPair = KeyFactory.getInstance("EC").let {
        KeyPair(it.generatePublic(X509EncodedKeySpec(bytes("server_public_x509"))),
            it.generatePrivate(PKCS8EncodedKeySpec(bytes("server_private_pkcs8"))))
    }

    fun server(): Ukey2ServerHandshake = Ukey2ServerHandshake(serverPair(), FixedRandom(bytes("server_nonce")))

    fun clientInit(change: (Ukey2ClientInit) -> Ukey2ClientInit): ByteArray {
        val original = Ukey2Message.ADAPTER.decode(bytes("client_init"))
        val changed = change(Ukey2ClientInit.ADAPTER.decode(requireNotNull(original.message_data)))
        return Ukey2Message(Ukey2MessageType.CLIENT_INIT, changed.encodeByteString()).encode()
    }

    fun context(server: Boolean, random: SecureRandom = SecureRandom()): D2DConnectionContextV1 {
        val session = bytes(if (server) "server_session_initial" else "client_session_initial")
        check(session.size == 73 && session[0].toInt() == 1)
        return D2DConnectionContextV1(session.copyOfRange(9, 41), session.copyOfRange(41, 73), random)
    }

    class FixedRandom(private vararg val values: ByteArray) : SecureRandom() {
        private var position = 0
        override fun nextBytes(bytes: ByteArray) {
            check(position < values.size && values[position].size == bytes.size)
            values[position++].copyInto(bytes)
        }
    }
}
