/*
 * Copyright (C) 2013-2017 microG Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.microg.gms.common;

public enum GmsService {
    UNKNOWN(-2),
    ANY(-1),
    GAMES(1, "com.google.android.gms.games.service.START", "com.google.android.gms.games.internal.connect.service.START"),
    PLUS(2, "com.google.android.gms.plus.service.START", "com.google.android.gms.plus.service.internal.START"),
    PANORAMA(3, "com.google.android.gms.panorama.service.START"),
    WALLET(4, "com.google.android.gms.wallet.service.BIND"),
    PEOPLE(5, "com.google.android.gms.people.service.START"),
    LOCATION(6),
    APP_STATE(7, "com.google.android.gms.appstate.service.START"),
    ADMOB(8, "com.google.android.gms.ads.service.START"),
    ACCOUNT(9, "com.google.android.gms.accounts.ACCOUNT_SERVICE"),
    CAST(10, "com.google.android.gms.cast.service.BIND_CAST_DEVICE_CONTROLLER_SERVICE"),
    DRIVE(11, "com.google.android.gms.drive.ApiService.START"),
    ADDRESS(12, "com.google.android.gms.identity.service.BIND"),
    CAR(13, "com.google.android.gms.car.service.START"),
    WEAR(14, "com.google.android.gms.wearable.BIND"),
    AUTH_PROXY(16, "com.google.android.gms.auth.service.START"),
    IDENTITY(15),
    FITNESS(17, "com.google.android.gms.fitness.GoogleFitnessService.START"),
    REMINDERS(18, "com.google.android.gms.reminders.service.START"),
    LIGHT_INDEX(19, "com.google.android.gms.icing.LIGHTWEIGHT_INDEX_SERVICE"),
    DEVICE_CONNECTIONS(20, "com.google.android.gms.deviceconnection.service.START"),
    APP_DATA_SEARCH(21, "com.google.android.gms.icing.INDEX_SERVICE"),
    REPORTING(22, "com.google.android.gms.location.reporting.service.START", "com.google.android.location.reporting.service.START"),
    GOOGLE_LOCATION_MANAGER(23, "com.google.android.location.internal.GoogleLocationManagerService.START"),
    PLAY_LOG(24, "com.google.android.gms.playlog.service.START"),
    DROID_GUARD(25, "com.google.android.gms.droidguard.service.START"),
    LOCKBOX(26, "com.google.android.gms.lockbox.service.START"),
    CAST_MIRRORING(27, "com.google.android.gms.cast_mirroring.service.START"),
    NETWORK_QUALITY(28, "com.google.android.gms.mdm.services.START"),
    FEEDBACK(29, "com.google.android.gms.feedback.internal.IFeedbackService"),
    SEARCH_ADMINISTRATION(30),
    AUTO_BACKUP(31, "com.google.android.gms.photos.autobackup.service.START"),
    SEARCH_QUERIES(32),
    GLOBAL_SEARCH_ADMIN(33),
    CLOUD_SAVE(34),
    UDC(35, "com.google.android.gms.udc.service.START"),
    SEARCH_CORPORA(36),
    DEVICE_MANAGER(37, "com.google.android.gms.mdm.services.DeviceManagerApiService.START"),
    PSEUDONYMOUS_ID(38, "com.google.android.gms.pseudonymous.service.START"),
    COMMON(39, "com.google.android.gms.common.service.START"),
    CLEARCUT_LOGGER(40, "com.google.android.gms.clearcut.service.START"),
    USAGE_REPORTING(41, "com.google.android.gms.usagereporting.service.START"),
    KIDS(42, "com.google.android.gms.kids.service.START"),
    DOWNLOAD(43, "com.google.android.gms.common.download.START"),
    SIGN_IN(44, "com.google.android.gms.signin.service.START"),
    SAFETY_NET(45, "com.google.android.gms.safetynet.service.START"),
    ADMOB_GSERVICES_VALUE(46, "com.google.android.gms.ads.gservice.START"),
    CONTEXT_MANAGER(47, "com.google.android.contextmanager.service.ContextManagerService.START"),
    AUDIO_MODEM(48, "com.google.android.gms.audiomodem.service.AudioModemService.START"),
    NEARBY(49, "com.google.android.gms.nearby.sharing.service.NearbySharingService.START"),
    LIGHTWEIGHT_NETWORK_QUALITY(50, "com.google.android.gms.herrevad.services.LightweightNetworkQualityAndroidService.START"),
    PHENOTYPE(51, "com.google.android.gms.phenotype.service.START"),
    VOICE_UNLOCK(52, "com.google.android.gms.speech.service.START"),

    NEARBY_CONNECTIONS(54, "com.google.android.gms.nearby.connection.service.START"),
    FIT_SENSORS(55, "com.google.android.gms.fitness.SensorsApi"),
    FIT_RECORDING(56, "com.google.android.gms.fitness.RecordingApi"),
    FIT_HISTORY(57, "com.google.android.gms.fitness.HistoryApi"),
    FIT_SESSIONS(58, "com.google.android.gms.fitness.SessionsApi"),
    FIT_BLE(59, "com.google.android.gms.fitness.BleApi"),
    FIT_CONFIG(60, "com.google.android.gms.fitness.ConfigApi"),
    FIT_INTERNAL(61, "com.google.android.gms.fitness.InternalApi"),
    NEARBY_MESSAGES(62, "com.google.android.gms.nearby.messages.service.NearbyMessagesService.START"),
    GOOGLE_HELP(63, "com.google.android.gms.googlehelp.service.GoogleHelpService.START"),
    CHECKIN_CONFIG(64, "com.google.android.gms.config.START"),
    PLACES_GEO_DATA(65, "com.google.android.gms.location.places.GeoDataApi"),
    IME_UPDATES(66),
    PLACES_PLACE_DETECTION(67, "com.google.android.gms.location.places.PlaceDetectionApi"),
    AUTH_CREDENTIALS(68, "com.google.android.gms.auth.api.credentials.service.START"),
    NEARBY_BOOTSTRAP(69, "com.google.android.gms.nearby.bootstrap.service.NearbyBootstrapService.START"),
    PLUS_INTERNAL(70),
    MAPS_API(71),
    TRUSTAGENT_TRUSTED_DEVICES(72),
    SEARCH_AUTH(73),
    ACCOUNT_STATUS(74),
    SMARTDEVICE_D2D_SOURCE_DEVICE(75, "com.google.android.gms.smartdevice.d2d.SourceDeviceService.START"),
    SMARTDEVICE_D2D_TARGET_DEVICE(76, "com.google.android.gms.smartdevice.d2d.TargetDeviceService.START"),
    APP_INVITE(77, "com.google.android.gms.appinvite.service.START"),
    SEARCH_NATIVE_API(78),
    WALLET_TAP_AND_PAY(79, "com.google.android.gms.tapandpay.service.BIND"),
    CHROME_SYNC(80, "com.google.android.gms.chromesync.service.START"),
    SMARTDEVICE_SETUP_ACCOUNTS_BOOTSTRAP(81, "com.google.android.gms.smartdevice.setup.accounts.AccountsService.START"),
    GSA(82),
    CAST_REMOTE_DISPLAY(83, "com.google.android.gms.cast.remote_display.service.START"),
    TRUSTAGENT(85, "com.google.android.gms.trustagent.StateApi.START"),
    TRUSTAGENT_STATE(85),
    YOUTUBE(86),
    AUTH_SIGN_IN(87),
    VISION(88),
    TRUSTAGENT_BRIDGE(89),
    BACKUP_STATS(90),
    AUTH_GOOGLE_SIGN_IN(91, "com.google.android.gms.auth.api.signin.service.START"),

    MEASUREMENT(93, "com.google.android.gms.measurement.START"),
    WEAVE_DEVICE(94),
    AD_MEASUREMENT(95),


    FREIGHTER(98, "com.google.android.gms.freighter.service.START"),
    WEAVE_MANAGEMENT(99),
    WEAVE_COMMAND(100),
    WEAVE_APP_ACCESS(101),
    WEAVE_EVENT(102),
    WEAVE_LOCAL_STATELESS_DEVICE(103),
    AUTH_AUTHZEN_KEY(104),
    SCREEN_CAPTURE(105),
    APP_INVITE_INTERNAL(106),
    AUTH_AUTHZEN_INTERNAL_DATA(107),
    AUTH_PROXIMITY(108),
    ACCOUNT_SETTINGS(109),
    GUNS(110, "com.google.android.gms.notifications.service.START"),
    BEACON(111, "com.google.android.gms.beacon.internal.IBleService.START"),
    FIREBASE_AUTH(112, "com.google.firebase.auth.api.gms.service.START"),
    APP_INDEXING(113, "com.google.android.gms.icing.APP_INDEXING_SERVICE"),
    WALLET_P2P(114),
    WALLET_P2P_INTERNAL(115),
    GASS(116, "com.google.android.gms.gass.START"),
    U2F_API(117),
    U2F_PRIVILEGED_API(118),
    U2F_ZERO_PARTY_API(119),
    WORK_ACCOUNT_API(120, "com.google.android.gms.auth.account.workaccount.START"),
    INSTANT_APPS(121, "com.google.android.gms.instantapps.START"),
    CAST_FIRST_PARTY(122, "com.google.android.gms.cast.firstparty.START"),
    ADMOB_CACHE(123, "com.google.android.gms.ads.service.CACHE"),
    BOOT_COUNT(124, "com.google.android.gms.clearcut.bootcount.service.START"),
    FIT_GOALS(125),
    SMS_RETRIEVER(126, "com.google.android.gms.auth.api.phone.service.SmsRetrieverApiService.START"),
    MOBILE_DATA_HUB(127),
    AUTH_ACCOUNT_TRANSFER(128),
    CRYPTAUTH_API(129, "com.google.android.gms.auth.cryptauth.cryptauthservice.START"),
    CHECKIN_API(130, "com.google.android.gms.checkin.START"),
    DYNAMIC_LINKS_API(131, "com.google.firebase.dynamiclinks.service.START"),
    FONT_API(132, "com.google.android.gms.fonts.service.START"),
    TEST_SUPPORT(133),
    LOCATION_SHARING(134),
    ROMANESCO(135, "com.google.android.gms.romanesco.service.START"),
    AUTH_MANAGED_EMM_API(136),
    NETWORK_SCORER(137),
    NETWORK_RECOMMENDATION(138),
    BRELLA(139, "com.google.android.gms.learning.trainer.START"),
    RESTORE_SESSION(140),
    PEER_DOWNLOAD_MANAGER(141),
    AUTH_PROXIMITY_DEVICE_SYNC(142),
    REACHABILITY(143),
    AUTH_PROXIMITY_SECURE_CHANNEL(144),
    PREDICT_ON_DEVICE(145),
    APP_PREVIEW_MESSAGING(146),
    LOCAL_RESTORE(147),
    FIDO2_API(148, "com.google.android.gms.fido.fido2.regular.START"),
    FIDO2_PRIVILEGED_API(149, "com.google.android.gms.fido.fido2.privileged.START"),
    TELEPHONY_SPAM(150),
    AUTH_UNCERTIFIED_DEVICE(151),
    MOBILE_DATA_DOWNLOAD(152, "com.google.android.mdd.service.START"),
    AUTH_ACCOUNT_DATA(153, "com.google.android.gms.auth.account.data.service.START"),
    AUDIT(154, "com.google.android.gms.audit.service.START"),
    CONSTELLATION(155, "com.google.android.gms.constellation.service.START"),
    GROWTH(156),
    SYSTEM_UPDATE(157, "com.google.android.gms.update.START_API_SERVICE"),
    MOBILE_DATA_PLAN(158),
    SMARTDEVICE_WIFI_HELPER(159),
    MOBSTORE_FILE(160, "com.google.android.mobstore.service.START"),
    CAST_API(161),
    CURATOR(162),
    USER_LOCATION(163, "com.google.android.gms.userlocation.service.START"),
    MOBILE_DATA_HUB_LISTENER(164),
    EXAMPLE(165),
    ADMOB_HTTP_CLIENT(166, "com.google.android.gms.ads.service.HTTP"),
    LANGUAGE_PROFILE(167, "com.google.android.gms.languageprofile.service.START"),
    MDNS(168, "com.google.android.gms.mdns.service.START"),
    NEARBY_SETUP(169),
    ANALYTICS(170),
    SUBSCRIPTIONS(171),
    FOLSOM(172, "com.google.android.gms.auth.key.retrieval.service.START"),
    SEMANTIC_LOCATION(173, "com.google.android.gms.semanticlocation.service.START_ODLH"),
    VEHICLE(174),
    BACKUP_NOW(175),
    AUTH_EARLY_UPDATE(176),
    AUTOFILL(177),
    MATCHSTICK(178),
    AUTH_CREDENTIALS_INTERNAL(179),
    FIDO2_ZERO_PARTY_API(180, "com.google.android.gms.fido.fido2.zeroparty.START"),
    G1_RESTORE(181, "com.google.android.gms.backup.G1_RESTORE"),
    G1_BACKUP(182, "com.google.android.gms.backup.G1_BACKUP"),
    CODELAB(183),
    DRIVING_MODE(184),
    OSS_LICENSES_SERVICE(185, "com.google.android.gms.oss.licenses.service.START"),
    CLEAR_CONTACT_INTERACTIONS_SERVICE(186),
    AUTH_MANAGED_POLICY_SERVICE(187),
    PAY_SECURE_ELEMENT_SERVICE(188, "com.google.android.gms.payse.service.BIND"),
    RCS(189, "com.google.android.gms.rcs.START"),
    SMARTDEVICE_POST_SETUP(190),
    CARRIER_AUTH(191, "com.google.android.gms.carrierauth.service.START"),
    SYSTEM_UPDATE_SINGLE_UESR(192, "com.google.android.gms.update.START_SINGLE_USER_API_SERVICE"),
    APPUSAGE(193, "com.google.android.gms.appusage.service.START"),
    NEARBY_SHARING(194, "com.google.android.gms.nearby.sharing.START_SERVICE"),
    ADMOB_CONSENT_SERVICE(195, "com.google.android.gms.ads.service.CONSENT_LOOKUP"),
    CREDENTIAL_MANAGER(196, "com.google.android.gms.credential.manager.service.firstparty.START"),
    SMS_RETRIEVER_INTERNAL(197, "com.google.android.gms.auth.api.phone.service.InternalService.START"),
    PAY(198, "com.google.android.gms.pay.service.BIND", "com.google.android.gms.pay.service.THIRD_PARTY"),
    ASTERISM(199, "com.google.android.gms.asterism.service.START"),
    MOBILE_SUBSCRIPTION(200),
    GMS_RESTORE(201, "com.google.android.gms.backup.GMS_MODULE_RESTORE"),
    FACS_CACHE(202, "com.google.android.gms.facs.cache.service.START"),
    ADMOB_SDK_SIGNAL(203),
    PLATFORM_CONFIGURATOR(204),
    RECAPTCHA(205, "com.google.android.gms.recaptcha.service.START"),
    DUOKIT_SERVICE(206),
    SYSTEM_UPDATE_TV_API(207),
    CONTACT_SYNC(208, "com.google.android.gms.people.contactssync.service.START"),
    FEEDBACK_CAR(209),
    SMARTDEVICE_SOURCE_DIRECT_TRANSFER(210),
    SMARTDEVICE_TARGET_DIRECT_TRANSFER(211),
    AUTH_API_IDENTITY_SIGNIN(212, "com.google.android.gms.auth.api.identity.service.signin.START"),
    IDENTITY_GIS_INTERNAL(213),
    FIDO_CREDENTIAL_STORE(214, "com.google.android.gms.fido.credentialstore.internal_service.START"),
    MDI_SYNC(215, "com.google.android.gms.mdisync.service.START"),
    EVENT_ATTESTATION(216, "com.google.android.gms.ads.identifier.service.EVENT_ATTESTATION"),
    GCONNECT_EXP(217),
    SCHEDULER(218, "com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE"),
    AUTH_API_IDENTITY_AUTHORIZATION(219, "com.google.android.gms.auth.api.identity.service.authorization.START"),
    FACS_INTERNAL_SYNC(220, "com.google.android.gms.facs.internal.service.START"),
    AUTH_CONFIG_SYNC(221, "com.google.android.gms.auth.config.service.START"),
    ENTERPRISE(222),
    AUTH_API_IDENTITY_CREDENTIAL_SAVING(223, "com.google.android.gms.auth.api.identity.service.credentialsaving.START"),
    GOOGLE_AUTH(224, "com.google.android.gms.auth.account.authapi.START"),
    ENTERPRISE_LOADER(225, "com.google.android.gms.enterprise.loader.service.START"),
    THUNDERBIRD(226, "com.google.android.gms.thunderbird.service.START"),


    BACKUP(229),
    BUGREPORT(230),
    CORE(231),
    CHIMERA_DEBUG(232),
    CHIMERA_COMPONENTS_TEST(233),
    AUTH_EASYUNLOCK(234),
    COMMON_ACCOUNT(235),
    NEARBY_EXPOSURE_NOTIFICATION(236, "com.google.android.gms.nearby.exposurenotification.START"),
    CONTACT_INTERACTIONS(237),
    PERMISSION(238),
    PSEUDONYMOUS(239),
    SIGNIN(240),
    SETUP_SERVICES(241),
    PHONESKY_RECOVERY(242),
    SMARTDEVICE(243),
    STATEMENT_SERVICE(244),
    SMART_PROFILE(245),
    TRON(246),
    SECURITY(247),

    GAMES_UPGRADE(249),
    SUBSCRIBED_FEEDS(250),
    WESTWORLD(251),
    OTA(252),
    PLACES(253),
    STATS(254),
    PLATFORM_DATA_INDEXER(255),
    CONTAINER(256),
    GMS_COMPLIANCE(257, "com.google.android.gms.gmscompliance.service.START"),
    AUTH_BLOCKSTORE(258, "com.google.android.gms.auth.blockstore.service.START"),
    COMMON_BASE(259),
    GROWTH_UPGRADEPARTY(260),
    ADSIDENTITY(261),
    FIDO_SOURCE_DIRECT_TRANSFER(262, "com.google.android.gms.fido.sourcedevice.service.START"),
    STREAM_PROTECT(263),
    CHIMERA(264),
    NEARBY_FAST_PAIR(265, "com.google.android.gms.nearby.fastpair.START"),

    COMMON_API(267),
    LIGHTER_MESSAGING(268, "com.google.android.gms.matchstick.lighter.service.START"),
    FIDO_TARGET_DIRECT_TRANSFER(269, "com.google.android.gms.fido.targetdevice.internal_service.START"),
    CLIENT_TELEMETRY(270, "com.google.android.gms.common.telemetry.service.START"),


    FIDO_CLIENT_UI(273),
    FIDO_SHARED_LIBRARY(274),
    SMARTDEVICE_SECOND_DEVICE_AUTH(275, "com.google.android.gms.setup.auth.SecondDeviceAuth.START"),
    AUTH_MAGICTETHER(276),
    LOCATION_SHARING_REPORTER(277, "com.google.android.gms.locationsharingreporter.service.START"),

    WALLET_OCR(279, "com.google.android.gms.ocr.service.START"),
    ALL(280),
    WALLET_OCR_INTERNAL(281, "com.google.android.gms.ocr.service.internal.START"),
    GSERVICES_API(282),
    FIND_MY_DEVICE(283),
    FIND_MY_DEVICE_SPOT(284),
    PO_TOKENS(285, "com.google.android.gms.potokens.service.START"),
    EXPOSURE_NOTIFICATION_PROMOS(286),
    FIDO_AUTHENTICATOR_SERVICE(287),
    CONNECTED_HOME(288),
    DIGITAL_CAR_KEYS(289, "com.google.android.gms.dck.service.START"),


    COMMUNAL(292),
    PRESENCE_MANAGER(293),
    TRUSTLET_ONBODY(294),
    TRUSTLET_PLACE(295),
    GROWTH_FEATUREDROPS(296),
    GEO_TIME_ZONE(297),
    NEARBY_UWB(298),
    GMSCORE_LOGGER(299),
    APP_SET_ID(300, "com.google.android.gms.appset.service.START"),
    NNAPI_DRIVER_MANAGER(301),
    CRED_SYNC(302),
    CHROME_SYNC_FIRST_PARTY(303),
    USONIA(304),
    THREADNETWORK(305, "com.google.android.gms.threadnetwork.service.START"),
    CODELAB_SEPARATE(306),
    TRUSTAGENT_AUTHENTICATORS(307),
    MODULE_INSTALL(308, "com.google.android.gms.chimera.container.moduleinstall.ModuleInstallService.START"),
    CHIMERA_BROTLI_STREAM(309),
    PERSONALSAFETY(310),
    GAME_PLATFORM(311),
    DTDI(312),
    GROWTH_UIFLOW(313),
    SEMANTIC_LOCATION_HISTORY(314, "com.google.android.gms.semanticlocationhistory.service.START", "com.google.android.gms.semanticlocationhistory.zeroparty.service.START"),
    INAPP_REACH(315, "com.google.android.gms.inappreach.service.START"),
    DEVICE_ACCOUNT(316),
    NEARBY_PRESENCE(317),
    ENTERPRISE_LOST_MODE(318),
    HOMEGRAPH(319),
    AUTH_MANAGED_WORK_PROFILE(320),
    MDOC_STORE(321, "com.google.android.gms.mdocstore.service.MDOC_STORE"),
    DEVICE_PERFORMANCE(322),


    MULTIPACKAGE_DEBUG(325),
    TIME(326),
    TRUSTAGENT_ACTIVE_UNLOCK(327),
    QUICKSTART(328),
    CORE_SETTINGS(329),
    PHOTOPICKER(330),
    SEALEDCOMPUTING(331),
    APPSEARCH(332),
    ESIM(333),
    APP_ERROR(334, "com.google.android.gms.apperrors.service.START_APP_ERROR"),
    ADID(335),

    HOME(336),

    MLBENCHMARK(339),
    MLBENCHMARK_INSTALLER(340),
    FACTORY_RESET_PROTECTION(341),
    NOTIFICATIONS(342),
    GOOGLE_AUTH_AANG(343, "com.google.android.gms.auth.aang.events.services.START"),

    ANTIFINGERPRINTING(345),
    CALLSTREAMING(346),
    FIDO2_FIRST_PARTY_API(347),
    MULTIDEVICE(348),
    GOOGLESETTINGS(349),
    HTTPFLAGS(350),
    SETUP_SERVICES_REMOTE_SETUP(351),
    IDENTITY_CREDENTIALS(352),
    AMBIENT_CONTEXT(353),
    SAFE_BROWSING(354),
    MULTIDEVICE_API_FEATURE_SETTINGS(355),
    MULTIDEVICE_API_PROFILE(356),
    DATA_COMPLIANCE(357),
    NOTIFICATIONS_REGISTRATION(358),
    SERVICE_ENTITLEMENT(359),
    CASTAUTH(360),
    BLINDAUTH(361),
    MLKIT_DOCSCAN_UI(362),
    AUTH_CREDENTIALS_FIDO2_AUTHENTICATOR(363),
    COBALT(364),
    TENSORGPS(365),
    NETWORKTRANSPARENCY(366),
    COMMUNAL_AUTH(367),
    CRONET(368),

    PLAY_INTEGRITY_API(370),
    PLAY_INTEGRITY_AUTOPROTECT(371),
    AQR(372),
    AUTH_MANAGED_DEVICE_POSTURE_SERVICE(373),

    CORE_NOTIFICATIONS(375),
    KIDS_AUTH(376),
    NUDGES(377),
    CAMERA_LOW_LIGHT(378),
    IDENTITY_FIDO_INTERNAL(379),
    RECAPTCHABASE(380),
    AUTH_RESTORE_CREDENTIAL(381),
    CONTACTKEYS(382),
    HEALTH_CONNECT_BACKUPS(383),
    SETUP_SERVICES_TOS_ACCEPTANCE(384),
    LOCATION_NETWORK(385, "com.google.android.gms.location.network.service.START"),
    SPATULA_SETTINGS(386),
    NOTIFICATIONS_CAPPING(387, "com.google.android.gms.notifications.capping.api.NotificationsCappingApiService.START"),
    CAMERA_FEATURE_COMBINATION_QUERY(388),
    AUTOMOTIVE_SETUP_SERVICES_INTERNAL(389),
    CRISISALERTS(390),

    CONTINUITY(392),
    SETUP_SERVICES_TOS_ACCEPTANCE_STATUS(393),
    SAMPLESETTINGS(394),
    MOTION(395),
    SIGNIFICANT_PLACES(396),
    SAFETY_CORE(397),
    MOTION_SICKNESS_ASSIST(398),
    CRYPTAUTH_AUTO_ENROLLMENT(399),
    CODELAB_HELLO_WORLD(400),
    CONTINUITY_API_CROSS_DEVICE(401),
    AUTH_API_IDENTITY_CREDENTIAL_PROVIDER(402),
    CORE_CUI_ADVISE(403),
    IDENTITY_GIS_PERSISTENT(404),
    EARLY_CHECK_IN_EXAMPLE(405),

    MULTIDEVICE_SYNC(407),

    MANAGESTORAGE(409),
    NATIVE_SANDBOX(410),
    MISSED_CALL_RETRIEVER(411),
    HEALTH_TRACKING(412),
    FAMILY_CONTEXTUAL_CARD(413),
    CLEARCUT_LOGGER_SAMPLING(414, "com.google.android.gms.clearcut.sampler.service.START"),
    TRACING(415),
    DEPENDENCY_INSTALLER(416),
    ADVANCED_PROTECTION(417),

    ACTION_LEARNER(419),
    PIXELPREDICTIONS(420),
    RESTRICTEDNETWORK(421),
    ACCESSIBILITY_DEEP_LINKS(422),
    SCREENREACTIONS(423),
    PERFETTO_PROCESSOR(424),
    GOOGLEONE(425),
    DEMO_ACCOUNT(426),
    IDENTITY_FIDO_FIRST_PARTY(427),
    PWM(428),
    FIREBASE_FPNV(429),
    TENSORGPS_DEBUG(430),
    THREADNETWORK_ZERO_PARTY_API(431),
    CAST_INTELLIGENT_DEVICE_SUGGESTIONS(432),
    SIGNATURE_VERIFICATION(433),
    WALLET_TAP_AND_PAY_SINGLE_USER(434),
    BANK_SCAM_WARNING(435),
    STORAGE_ESCALATION_CARD(436),
    INTRUSION_DETECTION(437),
    ACCOUNT_PROFILE(438),
    BACKUP_STATE(439),
    FILAMENT_SUPPORT_CHECKER(440),
    SPOON_PC(441),
    LOCATION_SHARING_API(442),
    MEMENTO(443),
    BUILD_HORIZON(444),
    CLEARCUT_LOG_MANAGER(445),

    NATIVE_HOTLOADER(447),
    TELEMETRY_NOTIFICATION(449, "com.google.android.gms.common.telemetry.notification.service.START"),
    ;

    public int SERVICE_ID;
    public String ACTION;
    public String[] SECONDARY_ACTIONS;

    GmsService(int serviceId, String... actions) {
        this.SERVICE_ID = serviceId;
        this.ACTION = actions.length > 0 ? actions[0] : null;
        this.SECONDARY_ACTIONS = actions;
    }

    public interface ADVERTISING_ID {
        // Has no service id
        String ACTION = "com.google.android.gms.ads.identifier.service.START";
    }

    public static GmsService byServiceId(int serviceId) {
        for (GmsService service : values()) {
            if (service.SERVICE_ID == serviceId) return service;
        }
        return UNKNOWN;
    }

    public static GmsService byAction(String action) {
        for (GmsService service : values()) {
            for (String serviceAction : service.SECONDARY_ACTIONS) {
                if (serviceAction.equals(action)) return service;
            }
        }
        return UNKNOWN;
    }

    public static String nameFromServiceId(int serviceId) {
        return byServiceId(serviceId).toString(serviceId);
    }

    public String toString(int serviceId) {
        if (this != UNKNOWN) return toString();
        return "UNKNOWN(" + serviceId + ")";
    }
}
