// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/snet.proto
package org.microg.gms.snet;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class AttestResponse extends Message {

  public static final String DEFAULT_RESULT = "";

  @ProtoField(tag = 2, type = STRING)
  public final String result;

  public AttestResponse(String result) {
    this.result = result;
  }

  private AttestResponse(Builder builder) {
    this(builder.result);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AttestResponse)) return false;
    return equals(result, ((AttestResponse) other).result);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = this.result != null ? this.result.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<AttestResponse> {

    public String result;

    public Builder() {
    }

    public Builder(AttestResponse message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
    }

    public Builder result(String result) {
      this.result = result;
      return this;
    }

    @Override
    public AttestResponse build() {
      return new AttestResponse(this);
    }
  }
}
