// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/snet.proto
package org.microg.gms.snet;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class SafetyNetData extends Message {

  public static final ByteString DEFAULT_NONCE = ByteString.EMPTY;
  public static final String DEFAULT_PACKAGENAME = "";
  public static final List<ByteString> DEFAULT_SIGNATUREDIGEST = Collections.emptyList();
  public static final ByteString DEFAULT_FILEDIGEST = ByteString.EMPTY;
  public static final Integer DEFAULT_GMSVERSIONCODE = 0;
  public static final List<FileState> DEFAULT_SUCANDIDATES = Collections.emptyList();
  public static final Long DEFAULT_CURRENTTIMEMS = 0L;
  public static final Boolean DEFAULT_GOOGLECN = false;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString nonce;

  @ProtoField(tag = 2, type = STRING)
  public final String packageName;

  @ProtoField(tag = 3, type = BYTES, label = REPEATED)
  public final List<ByteString> signatureDigest;

  @ProtoField(tag = 4, type = BYTES)
  public final ByteString fileDigest;

  @ProtoField(tag = 5, type = INT32)
  public final Integer gmsVersionCode;

  @ProtoField(tag = 6, label = REPEATED, messageType = FileState.class)
  public final List<FileState> suCandidates;

  @ProtoField(tag = 7)
  public final SELinuxState seLinuxState;

  @ProtoField(tag = 8, type = INT64)
  public final Long currentTimeMs;

  @ProtoField(tag = 9, type = BOOL)
  public final Boolean googleCn;

  public SafetyNetData(ByteString nonce, String packageName, List<ByteString> signatureDigest, ByteString fileDigest, Integer gmsVersionCode, List<FileState> suCandidates, SELinuxState seLinuxState, Long currentTimeMs, Boolean googleCn) {
    this.nonce = nonce;
    this.packageName = packageName;
    this.signatureDigest = immutableCopyOf(signatureDigest);
    this.fileDigest = fileDigest;
    this.gmsVersionCode = gmsVersionCode;
    this.suCandidates = immutableCopyOf(suCandidates);
    this.seLinuxState = seLinuxState;
    this.currentTimeMs = currentTimeMs;
    this.googleCn = googleCn;
  }

  private SafetyNetData(Builder builder) {
    this(builder.nonce, builder.packageName, builder.signatureDigest, builder.fileDigest, builder.gmsVersionCode, builder.suCandidates, builder.seLinuxState, builder.currentTimeMs, builder.googleCn);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SafetyNetData)) return false;
    SafetyNetData o = (SafetyNetData) other;
    return equals(nonce, o.nonce)
        && equals(packageName, o.packageName)
        && equals(signatureDigest, o.signatureDigest)
        && equals(fileDigest, o.fileDigest)
        && equals(gmsVersionCode, o.gmsVersionCode)
        && equals(suCandidates, o.suCandidates)
        && equals(seLinuxState, o.seLinuxState)
        && equals(currentTimeMs, o.currentTimeMs)
        && equals(googleCn, o.googleCn);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = nonce != null ? nonce.hashCode() : 0;
      result = result * 37 + (packageName != null ? packageName.hashCode() : 0);
      result = result * 37 + (signatureDigest != null ? signatureDigest.hashCode() : 1);
      result = result * 37 + (fileDigest != null ? fileDigest.hashCode() : 0);
      result = result * 37 + (gmsVersionCode != null ? gmsVersionCode.hashCode() : 0);
      result = result * 37 + (suCandidates != null ? suCandidates.hashCode() : 1);
      result = result * 37 + (seLinuxState != null ? seLinuxState.hashCode() : 0);
      result = result * 37 + (currentTimeMs != null ? currentTimeMs.hashCode() : 0);
      result = result * 37 + (googleCn != null ? googleCn.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SafetyNetData> {

    public ByteString nonce;
    public String packageName;
    public List<ByteString> signatureDigest;
    public ByteString fileDigest;
    public Integer gmsVersionCode;
    public List<FileState> suCandidates;
    public SELinuxState seLinuxState;
    public Long currentTimeMs;
    public Boolean googleCn;

    public Builder() {
    }

    public Builder(SafetyNetData message) {
      super(message);
      if (message == null) return;
      this.nonce = message.nonce;
      this.packageName = message.packageName;
      this.signatureDigest = copyOf(message.signatureDigest);
      this.fileDigest = message.fileDigest;
      this.gmsVersionCode = message.gmsVersionCode;
      this.suCandidates = copyOf(message.suCandidates);
      this.seLinuxState = message.seLinuxState;
      this.currentTimeMs = message.currentTimeMs;
      this.googleCn = message.googleCn;
    }

    public Builder nonce(ByteString nonce) {
      this.nonce = nonce;
      return this;
    }

    public Builder packageName(String packageName) {
      this.packageName = packageName;
      return this;
    }

    public Builder signatureDigest(List<ByteString> signatureDigest) {
      this.signatureDigest = checkForNulls(signatureDigest);
      return this;
    }

    public Builder fileDigest(ByteString fileDigest) {
      this.fileDigest = fileDigest;
      return this;
    }

    public Builder gmsVersionCode(Integer gmsVersionCode) {
      this.gmsVersionCode = gmsVersionCode;
      return this;
    }

    public Builder suCandidates(List<FileState> suCandidates) {
      this.suCandidates = checkForNulls(suCandidates);
      return this;
    }

    public Builder seLinuxState(SELinuxState seLinuxState) {
      this.seLinuxState = seLinuxState;
      return this;
    }

    public Builder currentTimeMs(Long currentTimeMs) {
      this.currentTimeMs = currentTimeMs;
      return this;
    }

    public Builder googleCn(Boolean googleCn) {
      this.googleCn = googleCn;
      return this;
    }

    @Override
    public SafetyNetData build() {
      return new SafetyNetData(this);
    }
  }
}
