// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/snet.proto
package org.microg.gms.snet;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class SELinuxState extends Message {

  public static final Boolean DEFAULT_SUPPORTED = false;
  public static final Boolean DEFAULT_ENABLED = false;

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean supported;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean enabled;

  public SELinuxState(Boolean supported, Boolean enabled) {
    this.supported = supported;
    this.enabled = enabled;
  }

  private SELinuxState(Builder builder) {
    this(builder.supported, builder.enabled);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SELinuxState)) return false;
    SELinuxState o = (SELinuxState) other;
    return equals(supported, o.supported)
        && equals(enabled, o.enabled);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = supported != null ? supported.hashCode() : 0;
      result = result * 37 + (enabled != null ? enabled.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SELinuxState> {

    public Boolean supported;
    public Boolean enabled;

    public Builder() {
    }

    public Builder(SELinuxState message) {
      super(message);
      if (message == null) return;
      this.supported = message.supported;
      this.enabled = message.enabled;
    }

    public Builder supported(Boolean supported) {
      this.supported = supported;
      return this;
    }

    public Builder enabled(Boolean enabled) {
      this.enabled = enabled;
      return this;
    }

    @Override
    public SELinuxState build() {
      return new SELinuxState(this);
    }
  }
}
