apply plugin: 'com.android.application'

android {
    namespace 'dev.rushi.locationtest'
    compileSdk androidCompileSdk

    defaultConfig {
        applicationId "dev.rushi.locationtest"
        minSdk androidMinSdk
        targetSdk androidTargetSdk
        versionCode 1
        versionName "1.0"

        manifestPlaceholders = [
                basePackageName: "$basePackageName"
        ]
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':play-services-location')
}
