/*
 * SPDX-FileCopyrightText: 2022 microG Project Team
 * SPDX-License-Identifier: Apache-2.0
 */

apply plugin: 'com.android.library'
apply plugin: 'com.squareup.wire'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'maven-publish'
apply plugin: 'signing'

dependencies {
    implementation project(':play-services-base-core')
    implementation project(':play-services-droidguard-core')
    implementation project(':play-services-safetynet-core')
    implementation project(':play-services-recaptcha')
    implementation project(':play-services-tasks-ktx')

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutineVersion"

    implementation "androidx.appcompat:appcompat:$appcompatVersion"
    implementation "androidx.core:core-ktx:$coreVersion"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-service:$lifecycleVersion"
    implementation "androidx.webkit:webkit:$webkitVersion"

    implementation "com.android.volley:volley:$volleyVersion"
    implementation "com.squareup.wire:wire-runtime:$wireVersion"

    implementation platform('androidx.compose:compose-bom:2024.04.00')
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.activity:activity-compose:1.8.2'

}

wire {
    kotlin {}
}

android {
    namespace "org.microg.gms.recaptcha.core"

    compileSdkVersion androidCompileSdk
    buildToolsVersion "$androidBuildVersionTools"

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.10"
    }

    defaultConfig {
        versionName version
        minSdkVersion androidMinSdk
        targetSdkVersion androidTargetSdk
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'MissingTranslation'
        disable 'CoroutineCreationDuringComposition'
    }

    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }

    kotlinOptions {
        jvmTarget = 1.8
    }
}

apply from: '../../gradle/publish-android.gradle'

description = 'microG service implementation for play-services-recaptcha'
