name: Docker Image CI

on:
  push:
    branches: [ Main-https/gitlab.com/AuroraOSS/AuroraStore/-/blob/captcha/README.md ]
  pull_request:
    branches: [ Main-https/gitlab.com/AuroraOSS/AuroraStore/-/blob/captcha/README.md ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
